/// <reference types="cypress" />

describe('Movies', () => {
//! Register test code block has been closed for testing because it will want to register the same mail address again.
  // it('Register page auth', () => {
  //   cy.visit('http://localhost:3000/register')
  //     .wait(2000)
  //     .url().should('include', '/register')
  //     .wait(2000)
  //     .get('#first-name')
  //     .type('cypress').should('have.value', 'cypress')
  //     .wait(2000)
  //     .get('#last-name')
  //     .type('test').should('have.value', 'test')
  //     .wait(2000)
  //     .get('#email')
  //     .type('cypress@test.com').should('have.value', 'cypress@test.com')
  //     .wait(2000)
  //     .get('#password')
  //     .type('cypress').should('have.value', 'cypress')
  //     .wait(2000)
  //     .get('#register > .btn').click()
  //     .wait(2000)
  // })

  // it('Logout auth', () => {
  //   cy.url().should('eq', 'http://localhost:3000/')
  //     .wait(2000)
  //     .get('.ms-2').click()

  // })

  it('Login page auth', () => {
    cy.visit('http://localhost:3000/login')
      .wait(4000)
      .get('#email')
      .type('cypress@test.com').should('have.value', 'cypress@test.com')
      .wait(2000)
      .get('#password')
      .type('cypress').should('have.value', 'cypress')
      .wait(2000)
      .get('#register > .btn').click()
      .wait(2000)
      .url().should('eq','http://localhost:3000/')
  })

  it('Search page', () => {
    cy.get('.search-input').type('The Matrix').should('have.value', 'The Matrix')
      .wait(2000)
      .get('.search > button').click()
      .wait(2000)
      .get('.flex-wrap > :nth-child(1) > img').click()
      .wait(3000)
      .get('.card-link').click()
      .wait(3000)
      .get('.search-input').type('Superman').should('have.value', 'Superman')
      .wait(2000)
      .get('.search > button').click()
      .wait(2000)
      .get('.card-link > .btn').click()
      .wait(2000)
      .get(':nth-child(20) > img').click()
      .wait(3000)
      .get('.card-link').click()
      .wait(2000)
      .get(':nth-child(2) > img').click()
      .wait(2000)
  })

  it('Detail page', () => {
    cy.url().should('eq','http://localhost:3000/list/details/1924')
      .wait(2000)
      .get('.card-body > div > :nth-child(3)').click()
      .wait(2000)
      .get('.commentBox > #exampleFormControlInput1').type('cypress test').should('have.value', 'cypress test')
      .wait(2000)
      .get('#exampleFormControlTextarea1').click().type('Hi, this comment was written by a cypress.').should('have.value', 'Hi, this comment was written by a cypress.')
      .wait(2000)
      .get('.commentBox > .btn').click()
      .wait(2000)
      .get('.accordion-button').click()
      .wait(2000)
      .get('.accordion-button').click()
      .wait(2000)
      .get(':nth-child(2) > .bi').click()
      .wait(2000)
      .get('[style="display: block; margin-right: 1rem;"] > #exampleFormControlInput1').click().type('cypress@test.com').should('have.value', 'cypress@test.com')
      .wait(2000)
      .get('[style="display: block; margin-right: 1rem;"] > .btn').click()
      .wait(2000)
      .get(':nth-child(1) > .bi').click()
      .wait(2000)
      .get('.logo').click()
      .wait(2000)
  })

  it('Logout', () => {
    cy.url().should('eq','http://localhost:3000/')
      .wait(2000)
      .get('.ms-2').click()
  })

})